### PR TITLE
16 add coverage build support

### LINKED ISSUE #16: Add coverage build support
* Update CMake build to support coverage builds
* Configure SPDK build with coverage support
* Modify build script to support coverage build option
* Update SPDK to support unit test builds with DSS

### PR DESCRIPTION
**Pull request by benixon**

### CODE REVIEW

**Comment by ramachaitanyak** [comment]
@benixon This looks good if it passes all the checks.

What would be useful is to have an updated README file somewhere (say here: https://github.com/OpenMPDK/dss-sdk or anywhere else you feel relevant) which will provide instructions on how to run code coverage and add future unit tests.

**Comment by benixon** [comment]
> @benixon This looks good if it passes all the checks.
> 
> What would be useful is to have an updated README file somewhere (say here: https://github.com/OpenMPDK/dss-sdk or anywhere else you feel relevant) which will provide instructions on how to run code coverage and add future unit tests.

Have added a brief update to Readme with build instructions

**Comment by ramachaitanyak** [comment]
This looks good to me. However do you folks; @velomatt @benixon @somnathr @hroogi think it might be a good idea to enable code coverage report on sonarcloud through this patch.

This is just a question, but should not be blocking the commit from my side.

**Review by ramachaitanyak — APPROVED** [review]
Looks good to me

**Pull request merged**
