### PR TITLE
Added rdd header files to the artifact

### PR DESCRIPTION
**Pull request by grandsuri**

### CODE REVIEW

**Comment by velomatt** [comment]
Please pull changes from `master`. This branch does not have up-to-date CI/CD.

**Comment by grandsuri** [comment]
FYI
The file `dss_sdk/host/src/openmpdk/PDK/core/src/api/include/rdd_cl.h` is split into two files `dss_sdk/utils/include/rdd_cl_api.h` and `dss_sdk/utils/rdd_cl/rdd_cl.h`. We need either the first file or the latter 2 files to compile client code.

Since the first file is in openmpdk repo, I just went with the 2 files in dss_sdk repo and added those 2 files to Makefile to copy into nkv-sdk-bin tar ball artifact.

**Review by velomatt — DISMISSED** [review]
Looks okay to me. I've confirmed these artifacts now appear in `include` in the artifact subdirectory for `nkv-sdk-bin`

**Comment by velomatt** [comment]
Contents of `host_out` post-build:
```
bash-4.2$ find host_out/ -name "*rdd*"
host_out/lib/librdd_cl.so
host_out/utils/rdd_cl
host_out/utils/rdd_cl/CMakeFiles/rdd_cl.dir
host_out/utils/rdd_cl/CMakeFiles/rdd_cl.dir/rdd_cl.c.d
host_out/utils/rdd_cl/CMakeFiles/rdd_cl.dir/rdd_cl.c.o
host_out/include/rdd_cl_api.h
host_out/include/rdd_cl.h
```

Contents of `nkv-sdk-bin` tarball:
```
bash-4.2$ find nkv-sdk -name "*rdd*"
nkv-sdk/include/rdd_cl_api.h
nkv-sdk/include/rdd_cl.h
nkv-sdk/lib/librdd_cl.so
nkv-sdk/conf/nkv_config_rdd.json
```

Assuming this is the expected behavior, I approve

**Review by velomatt — APPROVED** [review]
Approved - per my comments above

**Comment by grandsuri** [comment]
> Contents of `host_out` post-build:
> 
> ```
> bash-4.2$ find host_out/ -name "*rdd*"
> host_out/lib/librdd_cl.so
> host_out/utils/rdd_cl
> host_out/utils/rdd_cl/CMakeFiles/rdd_cl.dir
> host_out/utils/rdd_cl/CMakeFiles/rdd_cl.dir/rdd_cl.c.d
> host_out/utils/rdd_cl/CMakeFiles/rdd_cl.dir/rdd_cl.c.o
> host_out/include/rdd_cl_api.h
> host_out/include/rdd_cl.h
> ```
> 
> Contents of `nkv-sdk-bin` tarball:
> 
> ```
> bash-4.2$ find nkv-sdk -name "*rdd*"
> nkv-sdk/include/rdd_cl_api.h
> nkv-sdk/include/rdd_cl.h
> nkv-sdk/lib/librdd_cl.so
> nkv-sdk/conf/nkv_config_rdd.json
> ```
> 
> Assuming this is the expected behavior, I approve

Yes

**Pull request merged**
